This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (165 entries accepted, 0 rejected).
Sorting entries....done (1377 comparisons).
Generating output file thesis.acr....done (245 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
